/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EdFi.Roster.Sdk.Client.OpenAPIDateConverter;

namespace EdFi.Roster.Sdk.Models.Resources
{
    /// <summary>
    /// TpdmPerformanceEvaluationProgramGateway
    /// </summary>
    [DataContract(Name = "tpdm_performanceEvaluationProgramGateway")]
    public partial class TpdmPerformanceEvaluationProgramGateway : IEquatable<TpdmPerformanceEvaluationProgramGateway>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TpdmPerformanceEvaluationProgramGateway" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TpdmPerformanceEvaluationProgramGateway() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TpdmPerformanceEvaluationProgramGateway" /> class.
        /// </summary>
        /// <param name="programGatewayDescriptor">Identifies the program gateway that may be associated for continuation in the program. (required).</param>
        public TpdmPerformanceEvaluationProgramGateway(string programGatewayDescriptor = default(string))
        {
            // to ensure "programGatewayDescriptor" is required (not null)
            this.ProgramGatewayDescriptor = programGatewayDescriptor ?? throw new ArgumentNullException("programGatewayDescriptor is a required property for TpdmPerformanceEvaluationProgramGateway and cannot be null");
        }

        /// <summary>
        /// Identifies the program gateway that may be associated for continuation in the program.
        /// </summary>
        /// <value>Identifies the program gateway that may be associated for continuation in the program.</value>
        [DataMember(Name = "programGatewayDescriptor", IsRequired = true, EmitDefaultValue = false)]
        public string ProgramGatewayDescriptor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TpdmPerformanceEvaluationProgramGateway {\n");
            sb.Append("  ProgramGatewayDescriptor: ").Append(ProgramGatewayDescriptor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TpdmPerformanceEvaluationProgramGateway);
        }

        /// <summary>
        /// Returns true if TpdmPerformanceEvaluationProgramGateway instances are equal
        /// </summary>
        /// <param name="input">Instance of TpdmPerformanceEvaluationProgramGateway to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TpdmPerformanceEvaluationProgramGateway input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ProgramGatewayDescriptor == input.ProgramGatewayDescriptor ||
                    (this.ProgramGatewayDescriptor != null &&
                    this.ProgramGatewayDescriptor.Equals(input.ProgramGatewayDescriptor))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ProgramGatewayDescriptor != null)
                    hashCode = hashCode * 59 + this.ProgramGatewayDescriptor.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // ProgramGatewayDescriptor (string) maxLength
            if(this.ProgramGatewayDescriptor != null && this.ProgramGatewayDescriptor.Length > 306)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ProgramGatewayDescriptor, length must be less than 306.", new [] { "ProgramGatewayDescriptor" });
            }

            yield break;
        }
    }

}
