/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EdFi.Roster.Sdk.Client.OpenAPIDateConverter;

namespace EdFi.Roster.Sdk.Models.Resources
{
    /// <summary>
    /// TpdmFieldworkExperienceSectionAssociation
    /// </summary>
    [DataContract(Name = "tpdm_fieldworkExperienceSectionAssociation")]
    public partial class TpdmFieldworkExperienceSectionAssociation : IEquatable<TpdmFieldworkExperienceSectionAssociation>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TpdmFieldworkExperienceSectionAssociation" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TpdmFieldworkExperienceSectionAssociation() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TpdmFieldworkExperienceSectionAssociation" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="fieldworkExperienceReference">fieldworkExperienceReference (required).</param>
        /// <param name="sectionReference">sectionReference (required).</param>
        /// <param name="etag">A unique system-generated value that identifies the version of the resource..</param>
        public TpdmFieldworkExperienceSectionAssociation(string id = default(string), TpdmFieldworkExperienceReference fieldworkExperienceReference = default(TpdmFieldworkExperienceReference), EdFiSectionReference sectionReference = default(EdFiSectionReference), string etag = default(string))
        {
            // to ensure "fieldworkExperienceReference" is required (not null)
            this.FieldworkExperienceReference = fieldworkExperienceReference ?? throw new ArgumentNullException("fieldworkExperienceReference is a required property for TpdmFieldworkExperienceSectionAssociation and cannot be null");
            // to ensure "sectionReference" is required (not null)
            this.SectionReference = sectionReference ?? throw new ArgumentNullException("sectionReference is a required property for TpdmFieldworkExperienceSectionAssociation and cannot be null");
            this.Id = id;
            this.Etag = etag;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets FieldworkExperienceReference
        /// </summary>
        [DataMember(Name = "fieldworkExperienceReference", IsRequired = true, EmitDefaultValue = false)]
        public TpdmFieldworkExperienceReference FieldworkExperienceReference { get; set; }

        /// <summary>
        /// Gets or Sets SectionReference
        /// </summary>
        [DataMember(Name = "sectionReference", IsRequired = true, EmitDefaultValue = false)]
        public EdFiSectionReference SectionReference { get; set; }

        /// <summary>
        /// A unique system-generated value that identifies the version of the resource.
        /// </summary>
        /// <value>A unique system-generated value that identifies the version of the resource.</value>
        [DataMember(Name = "_etag", EmitDefaultValue = false)]
        public string Etag { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TpdmFieldworkExperienceSectionAssociation {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  FieldworkExperienceReference: ").Append(FieldworkExperienceReference).Append("\n");
            sb.Append("  SectionReference: ").Append(SectionReference).Append("\n");
            sb.Append("  Etag: ").Append(Etag).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TpdmFieldworkExperienceSectionAssociation);
        }

        /// <summary>
        /// Returns true if TpdmFieldworkExperienceSectionAssociation instances are equal
        /// </summary>
        /// <param name="input">Instance of TpdmFieldworkExperienceSectionAssociation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TpdmFieldworkExperienceSectionAssociation input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.FieldworkExperienceReference == input.FieldworkExperienceReference ||
                    (this.FieldworkExperienceReference != null &&
                    this.FieldworkExperienceReference.Equals(input.FieldworkExperienceReference))
                ) && 
                (
                    this.SectionReference == input.SectionReference ||
                    (this.SectionReference != null &&
                    this.SectionReference.Equals(input.SectionReference))
                ) && 
                (
                    this.Etag == input.Etag ||
                    (this.Etag != null &&
                    this.Etag.Equals(input.Etag))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.FieldworkExperienceReference != null)
                    hashCode = hashCode * 59 + this.FieldworkExperienceReference.GetHashCode();
                if (this.SectionReference != null)
                    hashCode = hashCode * 59 + this.SectionReference.GetHashCode();
                if (this.Etag != null)
                    hashCode = hashCode * 59 + this.Etag.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
