/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = EdFi.Roster.Sdk.Client.OpenAPIDateConverter;

namespace EdFi.Roster.Sdk.Models.Resources
{
    /// <summary>
    /// TpdmCandidateReference
    /// </summary>
    [DataContract(Name = "tpdm_candidateReference")]
    public partial class TpdmCandidateReference : IEquatable<TpdmCandidateReference>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TpdmCandidateReference" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TpdmCandidateReference() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TpdmCandidateReference" /> class.
        /// </summary>
        /// <param name="candidateIdentifier">A unique alphanumeric code assigned to a candidate. (required).</param>
        /// <param name="link">link.</param>
        public TpdmCandidateReference(string candidateIdentifier = default(string), Link link = default(Link))
        {
            // to ensure "candidateIdentifier" is required (not null)
            this.CandidateIdentifier = candidateIdentifier ?? throw new ArgumentNullException("candidateIdentifier is a required property for TpdmCandidateReference and cannot be null");
            this.Link = link;
        }

        /// <summary>
        /// A unique alphanumeric code assigned to a candidate.
        /// </summary>
        /// <value>A unique alphanumeric code assigned to a candidate.</value>
        [DataMember(Name = "candidateIdentifier", IsRequired = true, EmitDefaultValue = false)]
        public string CandidateIdentifier { get; set; }

        /// <summary>
        /// Gets or Sets Link
        /// </summary>
        [DataMember(Name = "link", EmitDefaultValue = false)]
        public Link Link { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TpdmCandidateReference {\n");
            sb.Append("  CandidateIdentifier: ").Append(CandidateIdentifier).Append("\n");
            sb.Append("  Link: ").Append(Link).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TpdmCandidateReference);
        }

        /// <summary>
        /// Returns true if TpdmCandidateReference instances are equal
        /// </summary>
        /// <param name="input">Instance of TpdmCandidateReference to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TpdmCandidateReference input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CandidateIdentifier == input.CandidateIdentifier ||
                    (this.CandidateIdentifier != null &&
                    this.CandidateIdentifier.Equals(input.CandidateIdentifier))
                ) && 
                (
                    this.Link == input.Link ||
                    (this.Link != null &&
                    this.Link.Equals(input.Link))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CandidateIdentifier != null)
                    hashCode = hashCode * 59 + this.CandidateIdentifier.GetHashCode();
                if (this.Link != null)
                    hashCode = hashCode * 59 + this.Link.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // CandidateIdentifier (string) maxLength
            if(this.CandidateIdentifier != null && this.CandidateIdentifier.Length > 32)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CandidateIdentifier, length must be less than 32.", new [] { "CandidateIdentifier" });
            }

            yield break;
        }
    }

}
